spring.application.name=backend
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=tm_database;encrypt=true;trustServerCertificate=true;
spring.datasource.username=admin
spring.datasource.password=admin
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
# spring.jpa.hibernate.ddl-auto=update

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
spring.jpa.open-in-view=false

spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml
# spring.datasource.url=jdbc:sqlserver://localhost\\SQLEXPRESS;databaseName=tm_database;trustedConnection=true